<?xml version="1.0"?>
<!-- iRobot Roomba 650 model -->
<robot name="roomba" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Robot form parameters -->
  <xacro:property name="PI" value="3.141592"/>
  <xacro:property name="wheels_offset" value="0.235"/>
  <xacro:property name="wheels_xgap" value="0.0"/>
  <xacro:property name="wheels_radius" value="0.036"/>
  <xacro:property name="wheels_width" value="0.015"/>
  <xacro:property name="wheels_mass" value="0.7"/>
  <xacro:property name="wheels_effort" value="1"/>
  <xacro:property name="wheels_velocity" value="1"/>
  <xacro:property name="wheels_damping" value="0.1"/>
  <xacro:property name="base_zgap" value="0.01"/>
  <xacro:property name="base_height" value="${0.083-base_zgap}"/>
  <xacro:property name="base_radius" value="0.174"/>
  <xacro:property name="base_mass" value="3.0"/>
  <xacro:property name="roller_radius" value="${base_zgap*1.0}"/>
  <xacro:property name="roller_xgap" value="0.135"/>
  <xacro:property name="ir_height" value="0.009"/>
  <xacro:property name="ir_radius" value="0.01"/>
  <xacro:property name="ir_mass" value="0.01"/>
  <xacro:property name="ir_xgap" value="0.15"/>
  <xacro:property name="lidar_radius" value="0.038"/>
  <xacro:property name="lidar_height" value="0.041"/>
  <!-- <xacro:property name="lidar_offset_y" value="0.105"/> -->
  <xacro:property name="lidar_offset_y" value="0.0"/>
  <xacro:property name="local_costmap_offset_x" value="2.0"/>
  <xacro:property name="local_costmap_offset_y" value="0.0"/>

  <!-- Macro definition for the inertial property of cylinders -->
  <xacro:macro name="cylinder_inertial" params="radius length mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass*radius*radius/2}" ixy="0.0" ixz="0.0"
               iyy="${mass*radius*radius/4+mass*length*length/12}" iyz="0.0"
               izz="${mass*radius*radius/4+mass*length*length/12}"/>
    </inertial>
  </xacro:macro>

  <!-- Include materials and gazebo extensions for compatibility -->
  <xacro:include filename="$(find robotics)/urdf/create2.gazebo" />
  <xacro:include filename="$(find robotics)/urdf/materials.xacro" />

  <!-- Definition of the main chassis projection at z=0 (for amcl and navigation purposes) -->
  <link name="base_footprint">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- Import mesh for robot -->
      <geometry>
        <mesh filename="package://robotics/meshes/base_create2.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${(base_height/2+base_zgap)}" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- Definition of the main (base) link of the robot -->
  <link name="base_link">
    <xacro:cylinder_inertial
      radius="${base_radius}" length="${base_height}" mass="${base_mass}"/>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
  </link>



  <!-- Lidar joint -->
  <joint name="lidar_joint" type="fixed">
    <origin xyz="0 ${lidar_offset_y} ${base_height/2+lidar_height/2}"
            rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="lidar"/>
  </joint>

  <!-- Lidar link -->
  <link name="lidar">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <!-- <cylinder radius="${lidar_radius}" length="${lidar_height}"/> -->
        <!-- Import lidar mesh -->
        <mesh filename="package://robotics/meshes/rplidar_a3m1.dae" />
      </geometry>
      <material name="purple"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
  </link>


  <!-- Front roller link -->
  <joint name="roller_joint" type="fixed">
    <origin xyz="${roller_xgap} 0 ${-base_height/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="roller"/>
  </joint>

  <link name="roller">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <!-- <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
      <material name="green_transparent"/>
    </visual> -->
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
    </collision>
  </link>

  <joint name="roller_joint_back" type="fixed">
    <origin xyz="${-roller_xgap} 0 ${-base_height/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="roller_back"/>
  </joint>

  <link name="roller_back">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
      <material name="green_transparent"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
    </collision>
  </link>



  <joint name="ir_joint" type="fixed">
    <origin xyz="${ir_xgap} 0 ${base_height/2+ir_height/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="ir"/>
  </joint>

  <link name="ir">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${ir_mass}"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <!-- <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${ir_radius}" length="${ir_height}"/>
      </geometry>
      <material name="red"/>
    </visual> -->
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${ir_radius}" length="${ir_height}"/>
      </geometry>
    </collision>
  </link>



  <!-- Right wheel -->
  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheels_mass}"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
    </collision>
  </link>



  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="${-wheels_xgap} ${-wheels_offset/2} ${-base_zgap-base_height/2+wheels_radius}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <dynamics damping="${wheels_damping}"/>
    <!-- <limit effort="${wheels_effort}" velocity="${wheels_velocity}" /> -->
  </joint>



  <!-- Left wheel -->
  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.25"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
    </collision>
  </link>



  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="${-wheels_xgap} ${wheels_offset/2} ${-base_zgap-base_height/2+wheels_radius}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <dynamics damping="${wheels_damping}"/>
    <!-- <limit effort="${wheels_effort}" velocity="${wheels_velocity}" /> -->
  </joint>


  <!-- <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->





</robot>
