global_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  inflation_radius: 2.0
  resolution: 0.05
  cost_scaling_factor: 15.0
