global_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 0.5
  publish_frequency: 1.0
  static_map: true
  inflation_radius: 3.0
  resolution: 0.1
  cost_scaling_factor: 15.0
