local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  # origin_x: -1.5
  # origin_y: -1.5
  resolution: 0.1
  inflation_radius: 0.5
  cost_scaling_factor: 10.0
